/*
 * SEVENSEGMENT_interface.h
 *
 * Created: 1/3/2024 11:00:00 PM
 * Author: Tarek Alaa
 */ 

#ifndef SEVEN_SEGMENT_INTERFACE_H_
#define SEVEN_SEGMENT_INTERFACE_H_

#include "STD_TYPES.h"
#include "BIT_MATH.h"


typedef struct
{
	u8 SEVENSEGMENT_MODE;
	u8 SEVENSEGMENT_TYPE;
	u8 SEVENSEGMENT_PORT;
	u8 SEVENSEGMENT_PINS[7];
}SEVENSEGMENT_CONFIG_t;

typedef enum 
{
	SEVENSEGMENT_4BINS,
	SEVENSEGMENT_8BINS
}SEVENSEGMENT_MODE_t;

typedef enum
{
	SEVENSEGMENT_COMMON_ANODE,
	SEVENSEGMENT_COMMON_CATHODE
}SEVENSEGMENT_TYPE_t;

typedef enum
{
	SEVENSEGMENT_PORTA,
	SEVENSEGMENT_PORTB,
	SEVENSEGMENT_PORTC,
	SEVENSEGMENT_PORTD
}SEVENSEGMENT_PORT_t;

typedef enum 
{
	SEVEN_SEGMENT_PIN0,
	SEVEN_SEGMENT_PIN1,
	SEVEN_SEGMENT_PIN2,
	SEVEN_SEGMENT_PIN3,
	SEVEN_SEGMENT_PIN4,
	SEVEN_SEGMENT_PIN5,
	SEVEN_SEGMENT_PIN6,
	SEVEN_SEGMENT_PIN7
}SEVENSEGMENT_PINS_t;

typedef enum 
{
	DISPLAY1_PORT,
	DISPLAY2_PORT,
	DISPLAY3_PORT,
	DISPLAY4_PORT
}SEVENSEGMENT_DISPLAYPORT_t;

typedef enum
{
	DISPLAY1_PIN,
	DISPLAY2_PIN,
	DISPLAY3_PIN,
	DISPLAY4_PIN
}SEVENSEGMENT_DISPLAYPIN_t;

void SEVENSEGMENT_voidInit();
void SEVENSEGMENT_voidDisplayNum(u16 copy_u8Number);
void SEVENSEGMENT_voidDisplayDigit(u16 copy_u8Digit, SEVENSEGMENT_DISPLAYPORT_t copy_enumDisplayPort,SEVENSEGMENT_DISPLAYPIN_t copy_enumDisplayPin);

#endif