/*
 * SEVEN_SEGMENT_config.h
 *
 * Created: 3/1/2024 2:27:51 PM
 *  Author: Tarek Alaa
 */ 


#ifndef SEVEN_SEGMENT_CONFIG_H_
#define SEVEN_SEGMENT_CONFIG_H_

#include "SEVEN_SEGMENT_interface.h"

#define SEVENSEGMENT_DISPLAY1_PORT  DIO_PORTB
#define SEVENSEGMENT_DISPLAY1_PIN   DIO_PIN6
		
#define SEVENSEGMENT_DISPLAY2_PORT  DIO_PORTB
#define SEVENSEGMENT_DISPLAY2_PIN   DIO_PIN5
		
#define SEVENSEGMENT_DISPLAY3_PORT  DIO_PORTA
#define SEVENSEGMENT_DISPLAY3_PIN   DIO_PIN2
		
#define SEVENSEGMENT_DISPLAY4_PORT  DIO_PORTA
#define SEVENSEGMENT_DISPLAY4_PIN   DIO_PIN3

#define SEVENSEGMENT_MULTIPLEXING   1

const SEVENSEGMENT_CONFIG_t SevenSegmentConfig ={
	.SEVENSEGMENT_MODE = SEVENSEGMENT_4BINS,
	.SEVENSEGMENT_TYPE = SEVENSEGMENT_COMMON_ANODE,
	.SEVENSEGMENT_PORT = SEVENSEGMENT_PORTB,
	.SEVENSEGMENT_PINS = {SEVEN_SEGMENT_PIN0,SEVEN_SEGMENT_PIN1,SEVEN_SEGMENT_PIN2,SEVEN_SEGMENT_PIN4},
	};

#endif /* SEVEN_SEGMENT_CONFIG_H_ */